# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: Heroku Deploy
      uses: AkhileshNS/heroku-deploy@v3.12.12
      env:
        # This will be used for authentication. You can find it in your heroku homepage account settings
        HEROKU-API-KEY: ${{ secrets.HEROKU_API_KEY }}
      run:
        heroku plugins: install java
        heroku deploy: jar build/libs/spring-todo-app-0.0.1-SNAPSHOT.jar --app glasshalffullstack--api


        # Email that you use with heroku
        # heroku_email: "adalynecummins@gmail.com"
        # The appname to use for deploying/updating
        # heroku_app_name: "glasshalffullstack--api"
